# Generated by Django 5.2.12 on 2026-03-30 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("doctor", "0001_initial"),
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabBill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("lab_bill_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "lab_bill_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_bills",
                        to="reception.patient",
                    ),
                ),
            ],
            options={
                "db_table": "lab_bills",
            },
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("overall_interpretation", models.TextField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_reports",
                        to="administration.staff",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="doctor.labtestrequest",
                    ),
                ),
            ],
            options={
                "db_table": "lab_reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="LabTestCatalog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("lab_test_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "lab_test_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("test_name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "test_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "lab_test_catalog",
                "ordering": ["test_name"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="lab_test_ca_status_2fde1f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabBillItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "lab_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="labtechinician.labbill",
                    ),
                ),
                (
                    "test_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="labtechinician.labtestcatalog",
                    ),
                ),
            ],
            options={
                "db_table": "lab_bill_items",
            },
        ),
        migrations.CreateModel(
            name="LabTestResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("parameter_name", models.CharField(max_length=100)),
                ("result_value", models.CharField(max_length=255)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reference_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_abnormal", models.BooleanField(default=False)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="doctor.labtestrequest",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_tests",
                        to="administration.staff",
                    ),
                ),
            ],
            options={
                "db_table": "lab_test_results",
            },
        ),
        migrations.AddIndex(
            model_name="labbill",
            index=models.Index(fields=["status"], name="lab_bills_status_4b618b_idx"),
        ),
        migrations.AddConstraint(
            model_name="labbillitem",
            constraint=models.UniqueConstraint(
                fields=("lab_bill", "test_catalog"), name="unique_test_per_bill"
            ),
        ),
        migrations.AddConstraint(
            model_name="labtestresult",
            constraint=models.UniqueConstraint(
                fields=("request", "parameter_name"),
                name="unique_parameter_per_request",
            ),
        ),
    ]
