# Generated by Django 5.2.12 on 2026-04-04 17:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtechinician', '0002_labtestparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbillitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
