# Generated by Django 5.2.12 on 2026-03-30 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("med_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "medicine_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("med_name", models.CharField(max_length=150)),
                ("company_name", models.CharField(max_length=150)),
                ("generic_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "medicines",
                "ordering": ["med_name"],
            },
        ),
        migrations.CreateModel(
            name="MedicineInventory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_number", models.CharField(max_length=50)),
                ("supplier_name", models.CharField(max_length=150)),
                ("purchased_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("quantity_available", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_batches",
                        to="pharmacist.medicine",
                    ),
                ),
            ],
            options={
                "db_table": "medicine_inventory",
                "ordering": ["-expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyBill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "pharmacy_bill_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "pharmacy_bill_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "prescription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_bill",
                        to="doctor.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_bills",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyBillItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "pharmacy_bill_item_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="pharmacist.medicineinventory",
                    ),
                ),
                (
                    "pharmacy_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="pharmacist.pharmacybill",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_bill_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="medicineinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("medicine", "batch_number"),
                name="unique_medicine_batch",
            ),
        ),
    ]
