"""
Django settings for CMS project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@2u5cyz+o65dz-jjf7h-&2qdc9r%yhh4w8ck9jw_*vc!vz+=a4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'authentication',
    'administration',
    'reception',
    'doctor',
    'pharmacist',
    'labtechinician',
    'common',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    "django_filters",
    'corsheaders',
]

# ─────────────────────────────────────────────────────────────────────────────
# CACHE — access token blacklist + DRF throttling
#
# Two backends are supported:
#   • Redis  (production / when REDIS_URL env var is set or Redis is running)
#   • LocMem (development fallback — no external server required)
#
# How the selection works:
#   Set USE_REDIS=1 in the environment to force Redis.
#   Otherwise the code tries to import django_redis; if that fails it falls
#   back to LocMemCache so the server starts without any external dependency.
#
# Security note for LocMem mode:
#   Blacklisted tokens are stored in process memory.  They survive for the
#   remainder of the 30-minute access-token lifetime and are enforced correctly
#   within a single server process.  On process restart the in-memory blacklist
#   is cleared — acceptable for development; NOT acceptable for production.
# ─────────────────────────────────────────────────────────────────────────────
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/1")

def _build_cache_config():
    """Return the best available cache backend configuration."""
    use_redis = os.environ.get("USE_REDIS", "").strip() == "1"

    if use_redis:
        # Explicit opt-in — fail loudly if django_redis is missing.
        return {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": REDIS_URL,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "SOCKET_CONNECT_TIMEOUT": 0.2,
                    "SOCKET_TIMEOUT": 0.2,
                    "IGNORE_EXCEPTIONS": False,
                },
                "KEY_PREFIX": "cms",
            }
        }

    try:
        import django_redis  # noqa: F401  — just checking availability
        # django_redis is installed; use Redis if the server is reachable.
        return {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": REDIS_URL,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "SOCKET_CONNECT_TIMEOUT": 0.2,
                    "SOCKET_TIMEOUT": 0.2,
                    # Suppress connection errors so a missing dev Redis server
                    # degrades to cache-miss behaviour rather than a 500.
                    # The token_blacklist module adds its own fail-safe on top.
                    "IGNORE_EXCEPTIONS": True,
                },
                "KEY_PREFIX": "cms",
            }
        }
    except ImportError:
        # django_redis not installed — use in-process memory cache.
        # Suitable for development only.
        import warnings
        warnings.warn(
            "django_redis is not installed. Falling back to LocMemCache. "
            "Token blacklist will not persist across server restarts. "
            "Install django_redis and run a Redis server for production.",
            stacklevel=2,
        )
        return {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "cms-token-blacklist",
            }
        }

CACHES = _build_cache_config()

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (
        # Custom class that checks Redis blacklist before accepting any token.
        # Replaces the default JWTAuthentication — interface is identical.
        "common.authentication.BlacklistAwareJWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    
    "DEFAULT_RENDERER_CLASSES": (
        "common.renderers.StandardizedJSONRenderer",
    ),

    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",
    
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        "login": "10/minute",
        "anon": "10/minute",
        "user": "100/minute",
    },
    
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    
    "PAGE_SIZE": 100
}

SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",

    # simplejwt includes jti by default; naming it explicitly keeps intent clear.
    # The Redis blacklist key is built from this claim: "bl:at:<jti>"
    "JTI_CLAIM": "jti",
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'common.middleware.CustomSecurityMiddleware',  # Custom security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

ROOT_URLCONF = 'CMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8}
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
CORS_ORIGIN_ALLOW_ALL = True
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING
# email_service logger writes to console + audit.log so email events are
# always traceable even when SMTP is not configured (console-mode dev).
# ─────────────────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'audit_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'audit.log',
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'email_service': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}