# Generated by Django 5.2.12 on 2026-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="duty_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ON_DUTY", "On Duty"),
                    ("OFF_DUTY", "Off Duty"),
                ],
                db_index=True,
                default="AVAILABLE",
                help_text="Current duty status of the doctor",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("ON_LEAVE", "On Leave"),
                ],
                db_index=True,
                default="ACTIVE",
                help_text="Operational status of the staff member",
                max_length=20,
            ),
        ),
    ]
