# Generated by Django 5.2.12 on 2026-04-04 17:07

import administration.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_on_duty_fix_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid Indian phone number (10 digits starting with 6–9, optional +91).', regex='^(\\+91)?[6-9]\\d{9}$'), administration.models.validate_phone_no_repeated_digits]),
        ),
    ]
