# Generated by Django 5.2.12 on 2026-03-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
        ("labtechinician", "0001_initial"),
        ("pharmacist", "0001_initial"),
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtestrequest",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_test_requests",
                to="labtechinician.labtestcatalog",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescription",
                to="reception.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescription_items",
                to="pharmacist.medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="doctor.prescription",
            ),
        ),
        migrations.AddConstraint(
            model_name="labtestrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("appointment", "lab_test"),
                name="doctor_labtestrequest_unique_active_test",
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("prescription", "medicine"),
                name="doctor_prescriptionitem_unique_medicine_per_prescription",
            ),
        ),
    ]
