# Generated by Django 5.2.12 on 2026-03-30 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "patient_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?\\d{10,15}$")
                        ],
                    ),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?\\d{10,15}$")
                        ],
                    ),
                ),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "patients",
                "indexes": [
                    models.Index(fields=["phone"], name="patients_phone_ef6690_idx"),
                    models.Index(
                        fields=["patient_code"], name="patients_patient_74efca_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="patients_is_dele_e0230d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("phone",),
                        name="unique_active_patient_phone",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "appointment_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("token_number", models.PositiveIntegerField(editable=False)),
                ("appointment_date", models.DateField(db_index=True)),
                ("appointment_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="administration.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="reception.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationBill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "consultation_bill_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "bill_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultation_bill",
                        to="reception.appointment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("consultation_fee__gte", 0)),
                        name="consultation_fee_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("registration_fee__gte", 0)),
                        name="registration_fee_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_amount__gte", 0)),
                        name="consultation_bill_total_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="bill_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("paid_at__isnull", False), ("status", "PAID")),
                            models.Q(("status", "PAID"), _negated=True),
                            _connector="OR",
                        ),
                        name="paid_requires_timestamp",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("doctor", "appointment_date", "token_number"),
                name="unique_token_per_doctor_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("doctor", "appointment_date", "appointment_time"),
                name="unique_timeslot_per_doctor",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("token_number__gt", 0)), name="token_positive_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="appointment_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", False), ("status", "COMPLETED")),
                    models.Q(("status", "COMPLETED"), _negated=True),
                    _connector="OR",
                ),
                name="completed_requires_timestamp",
            ),
        ),
    ]
