# Generated by Django 5.2.12 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Patient email for notifications",
                max_length=254,
                null=True,
            ),
        ),
    ]
