# Generated by Django 5.2.12 on 2026-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0002_add_patient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_status",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered"),
                    ("UNDER_CARE", "Under Care"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="REGISTERED",
                help_text="Current patient lifecycle status",
                max_length=20,
            ),
        ),
    ]
